# Site settings
title: hynes.barbour.io
description: 'James Hynes is a loser'
url: 'http://hynes.barbour.io' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Karl Barbour'
  email: karl@barbour.io
  github_username:  karl-barbour
  linkedin_username:  karlbarbour

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
