# Site settings
title: hynes.barbour.io
description: 'James Hynes Test Site'
url: 'http://hynes.barbour.io' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'James Hynes'
  email: jayhynzy1@hotmail.co.uk
  github_username:  Hynes-J
  

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
