# Site settings
title: barbour.io
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://karl-barbour.github.io' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Karl Barbour'
  email: karl@barbour.io
  twitter_username: x
  github_username:  karl-barbour
  linkedin_username:  karlbarbour

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
